### ISSUE TITLE
Documentation or Functionality broken

### ISSUE THREAD

**Issue by steowens** [NCR-Shi/pdf417#2]
With latest code from npm install, following the Usage instructions in the READ me does not result in any image with a bar code being displayed.

**Comment by NCR-Shi** [comment]
@steowens Sorry for the late response. I've used the package in my project for a long time and the barcode  seems fine to me. Can you provide more details to reproduce your case?

**Comment by steowens** [comment]
Sorry, but I have deleted that project and went to a different one.  I am not in a position to reproduce the issue.
